// lib/utils/pdf-generator.ts
import jsPDF from "jspdf";
import QRCode from "qrcode";
import { buildVerificationPayload, generateDocumentHash } from "./crypto";

type DocumentType = "PURCHASE_ORDER" | "COMPANY_WAYBILL";

export async function generateSecurePDF(poData: any, docType: DocumentType) {
  const issuedAt = new Date().toISOString();

  // 1. Create the verification payload & cryptographic hash
  const verificationPayload = buildVerificationPayload({
    poNumber: poData.po_number,
    vendorName: poData.vendors?.company_name || "",
    customerName: poData.customers?.company_name || "",
    docType,
    issuedAt,
  });

  const hash = await generateDocumentHash(verificationPayload);
  
  // The URL that the QR code will point to for live verification
  // In production, NEXT_PUBLIC_SITE_URL would be your actual domain
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://srks-system.vercel.app";
  const verifyUrl = `${siteUrl}/verify?hash=${hash}&po=${poData.po_number}&docType=${docType}&issuedAt=${encodeURIComponent(issuedAt)}`;

  // 2. Generate Base64 QR Code
  const qrCodeDataUrl = await QRCode.toDataURL(verifyUrl, {
    errorCorrectionLevel: 'H',
    margin: 1,
    width: 100,
  });

  // 3. Initialize PDF Canvas (A4 Portrait)
  const doc = new jsPDF({ format: "a4", unit: "mm" });

  // --- HEADER SECTION ---
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(6, 78, 59); // Emerald-900
  doc.text("SRKS ENTERPRISE PLC", 20, 25);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text("Lekki Free Trade Zone, Lagos, Nigeria", 20, 32);
  doc.text("RC: 1099238 | TIN: 002934-0001", 20, 37);

  // --- DOCUMENT TITLE ---
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(15, 23, 42); // Slate-900
  const title = docType === "PURCHASE_ORDER" ? "OFFICIAL PURCHASE ORDER" : "OUTBOUND DELIVERY WAYBILL";
  doc.text(title, 20, 55);

  // --- METADATA SECTION ---
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`Reference No: ${poData.po_number}`, 20, 65);
  doc.text(`Date Issued: ${new Date().toLocaleDateString('en-GB')}`, 20, 71);
  doc.text(`Target Facility: ${poData.customers?.company_name || "N/A"}`, 20, 77);
  
  if (docType === "PURCHASE_ORDER") {
    doc.text(`Assigned Vendor: ${poData.vendors?.company_name || "N/A"}`, 20, 83);
    doc.text(`Logistics Routing: ${poData.logistics_type?.toUpperCase() || "N/A"}`, 20, 89);
  }

  // --- CONTENT DIVIDER ---
  doc.setDrawColor(200, 200, 200);
  doc.line(20, 95, 190, 95);

  // --- LINE ITEMS (Simulated Table) ---
  doc.setFont("helvetica", "bold");
  doc.text("Authorized Consignment Details:", 20, 105);
  
  doc.setFont("helvetica", "normal");
  doc.text("For security, quantities and routing have been electronically verified.", 20, 112);
  
  // Note: In a full app, you would fetch `po_items` and loop through them here using `doc.text()`
  // For this implementation, we will stamp an authorization block.
  doc.setFillColor(248, 250, 252);
  doc.rect(20, 120, 170, 30, 'F');
  doc.setTextColor(15, 23, 42);
  doc.text("STATUS: AUTHORIZED FOR DISPATCH", 25, 130);
  doc.text(`DESTINATION: ${poData.customers?.delivery_address_default || "Registered Facility"}`, 25, 138);

  // --- FOOTER & CRYPTOGRAPHIC VERIFICATION ---
  doc.line(20, 240, 190, 240);
  
  // Paint QR Code
  doc.addImage(qrCodeDataUrl, "PNG", 20, 245, 30, 30);
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(6, 78, 59);
  doc.text("SECURE SYSTEM VERIFICATION", 55, 252);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text("This document was generated by the SRKS Enterprise Ledger.", 55, 258);
  doc.text("Scan the QR code to verify authenticity and prevent documentation fraud.", 55, 263);
  
  doc.setFont("courier", "normal");
  doc.setFontSize(7);
  doc.text(`SHA-256 HASH: ${hash}`, 55, 270);

  // 4. Trigger Download
  doc.save(`${poData.po_number}_${docType}.pdf`);
}